version: '3.5'
services:
  web-content-mysql:
    image: mysql:5.7
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
       - "/root/wm/conf/mysql/my.cnf:/etc/mysql/conf.d/local_my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${root_mysql}
    networks:
      - backend
  wordpress:
    depends_on:
      - web-content-mysql
    image: wordpress:4.9.7
    restart: always
    volumes:
      - wp_content:/var/www/html
    environment:
      WORDPRESS_DB_HOST: web-content-mysql:3306
      WORDPRESS_DB_PASSWORD: ${root_mysql}
    ports:
      - 8080:80
    networks:
      - backend
  nginx-proxy:
    depends_on:
      - wordpress
    image: nginx:stable
    restart: always
    volumes:
       - "/root/wm/conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
      - 4043:4043
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - web-content-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9080:80
    environment:
      PMA_HOST: web-content-mysql
      MYSQL_ROOT_PASSWORD: ${root_mysql}
    networks:
      - backend
networks:
  backend:
volumes:
  mysql_data:
  wp_content:
